### ISSUE TITLE
 I used it to successfully train a Chinese Mandarin model.But something went wrong...

### ISSUE THREAD

**Issue by zhjy8827** [mkotha/WaveRNN#10]
Hello, thank you very much for the code you provided. I used it to successfully train a Chinese Mandarin model. The training process is all right.
![image](https://user-images.githubusercontent.com/38745522/58558762-39cb4f80-8254-11e9-93a6-09fc49e2a9f6.png)
![image](https://user-images.githubusercontent.com/38745522/58558775-40f25d80-8254-11e9-8399-83e11f183a95.png)
But something went wrong...
When I synthesized the audio, I found that he had a chance to have an empty audio(Probability is about 40%), and it had no content:
When the audio is empty, the batch size is always equal to 1
![image](https://user-images.githubusercontent.com/38745522/58558799-4a7bc580-8254-11e9-9a2a-9e4a04b9984c.png)
Can you give some advice?Thank you!

[hparams.py.zip](https://github.com/mkotha/WaveRNN/files/3232541/hparams.py.zip)

**Comment by MlWoo** [comment]
I think there is a bug in the code. although there is mask to make that only the low half part of the r_t has connection with the current coarse input, and r_t will multiply the h_t-1 point-wisely and then matrix-multiply the R_e. so the current coarse input will conduct its influence on e_t not only low half part but also high half part by matrix-multiply operation. In other words, the code will infer the current coarse output with the current coarse input. So it will fails when synthesising.

**Comment by hdmjdp** [comment]
> I think there is a bug in the code. although there is mask to make that only the low half part of the r_t has connection with the current coarse input, and r_t will multiply the h_t-1 point-wisely and then matrix-multiply the R_e. so the current coarse input will conduct its influence on e_t not only low half part but also high half part by matrix-multiply operation. In other words, the code will infer the current coarse output with the current coarse input. So it will fails when synthesising.

I think this is not right. I think there is no imformation about coarse in r_t. Because you have filter it using mask. When r_t is transmited to next, e_t do not have coarse information in the high part.
