### ISSUE TITLE
How many iterations to train VQ-VAE?

### ISSUE THREAD

**Issue by Hiroshiba** [mkotha/WaveRNN#6]
I'm trying to train VQ-VAE with my dataset.
I want to know about how long it will take (ex. your great audio samples).

**Comment by mkotha** [comment]
The model used for the audio sample was trained for 945k steps.

**Comment by Hiroshiba** [comment]
Thanks!
I trained with my dataset, and after about 500k steps, I got generated speech that can get the words.
